---
title: "Create a spreadsheet"
execute:
  echo: false
bibliography: "../../modules/references.bib"
---

## Step 1: Read "Data organization in spreadsheets"

1. Read @broman2018data: ["Data organization in spreadsheets"](https://www.tandfonline.com/doi/full/10.1080/00031305.2017.1375989).

## Step 2: Make a spreadsheet and save it

Layout a spreadsheet for data collection using a spreadsheet-based software (Google Sheets or MS Excel). 

You are taking 20 samples of 1 liter faecal sludge from pit latrines and septic tanks at households and public toilets (5 samples each). For each sample, you note the number of daily users of the sanitation system. 

Your sample collection starts on 1st November 2022. On day 5, you analyse the data in the laboratory for totals solids (TS) in g/L. In your spreadsheet, note the exact date of each collected sample.

This is you data collection plan:

- Day 1: 5 samples at households using pit latrines
- Day 2: 5 samples at households using septic tanks
- Day 3: 5 samples at public toilets that are pit latrines
- Day 4: 5 samples at public toilets that are septic tanks
- Day 5: Analyses of all 20 samples for total solids (TS) in g/L on a lab scale with accuracy of 0.01 g

Make up the resultsfor the total solids (TS) analyses (e.g. 12.48 g/L).

Save the spreadsheet as XLSX with a file name of your choice.

## Step 3: Upload the spreadsheet to repository

1. Upload this spreadsheet as a CSV to the `data-raw` folder of your repository that was created for the data package.

## Step 4: Open an issue in your repository

1. Open an issue in your data repository with the title "Created a spreadsheet for data" and tag me `@larnsce`.

